---
title: Probability
author: David Kane and Ivy Spratt
tutorial:
  id: probability
output:
  learnr::tutorial:
    progressive: yes
    allow_skip: yes
runtime: shiny_prerendered
description: "Tutorial #01 for Preceptor's Primer"
---

```{r setup, include = FALSE}
library(learnr)
library(tutorial.helpers)
library(gt)

library(tidyverse)
library(primer.data)

knitr::opts_chunk$set(echo = FALSE)
options(tutorial.exercise.timelimit = 60,
        tutorial.storage = "local")
```

```{r copy-code-chunk, child = system.file("child_documents/copy_button.Rmd", package = "tutorial.helpers")}
```

```{r info-section, child = system.file("child_documents/info_section.Rmd", package = "tutorial.helpers")}
```


## Introduction

<!-- Tutorial content to be authored. The Cardinal Virtues "intellectual exercise" content that used to live here has been moved to 04-cardinal-virtues; this tutorial will be rebuilt around the actual probability content (distributions, simulation, joint/conditional) from book/01-probability.qmd. -->


## Summary


```{r download-answers, child = system.file("child_documents/download_answers.Rmd", package = "tutorial.helpers")}
```
