---
title: "Resumes: Wisdom and Justice"
format:
  html: default
execute:
  echo: false
---

```{r}
#| label: setup
#| message: false

library(tidyverse)

resumes <- read_csv("data/resumes.csv", show_col_types = FALSE) |>
  mutate(call = as.factor(call))
```

## The Question

There are two scenarios. Focus on just one of them:

- Imagine that you are a contemporary historian studying US employment in the year 2000 in Baltimore. You want to understand the process by which some people got jobs and some did not.

- Imagine that you work for a civil rights organization in Chicago. You want to understand the process by which black US citizens are discriminated against in hiring today.

The historian asks: What proportion of job applicants in Baltimore in the year 2000 received callbacks, and how did that proportion differ by the applicant's race and sex?

The civil rights organization asks: What is the average causal effect of having a black-sounding name, rather than a white-sounding name, on the probability that a job applicant in Chicago today receives a callback?

## Wisdom

### Preceptor Table

**What are the units, outcome, and covariates for your scenario's question?**

- Units:



- Outcomes:



- Covariates:



- Treatment (if any):



- Quantity of interest:



Describe the key components of a Preceptor Table for your scenario; Use words like "units," "outcomes," and "covariates."



### Exploratory Data Analysis

Create a plot that shows the distribution of `call`.



Create a plot that shows the relationship between `call` and `ethnicity`.



------------------------------------------------------------------------

## Justice

### Population Table

Describe the key components of a Population Table for your scenario.



### Assumptions

Counter-example to the assumption of validity:



Counter-example to the assumption of stability:



Counter-example to the assumption of representativeness:



Counter-example to the assumption of unconfoundedness:



### Probability Family and Link Function

What probability family should we use?



Why should we use that probability family?



What is the link function for our outcome?



------------------------------------------------------------------------
