# Fast Quarto book building with r2u container + renv
name: Build and Deploy Book

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container: rocker/r2u:latest
    
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Restore R packages with renv
        run: R -q -e 'renv::restore()'

      - name: Render book to docs directory
        run: quarto render --output-dir docs

      - name: Deploy to docs directory
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git diff --staged --quiet || (git commit -m "Update rendered book" && git push)